"use client";
/* eslint-disable jsx-a11y/label-has-associated-control */

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { jsPDF } from "jspdf";

export type InventoryItem = { id:string; title:string; description:string; room:string; width:number; depth:number; height:number; quantity:number; includeInPlan:boolean; photo?:string; updatedAt:string };
const DB_NAME="wohnungsplaner-inventar", STORE="items";
function openDb():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>request.result.createObjectStore(STORE,{keyPath:"id"});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function readItems():Promise<InventoryItem[]>{const db=await openDb();return new Promise<InventoryItem[]>((resolve,reject)=>{const request=db.transaction(STORE,"readonly").objectStore(STORE).getAll();request.onsuccess=()=>resolve((request.result as InventoryItem[]).map(item=>({...item,includeInPlan:item.includeInPlan!==false})));request.onerror=()=>reject(request.error)}).finally(()=>db.close())}
async function writeItem(item:InventoryItem){const db=await openDb();await new Promise<void>((resolve,reject)=>{const request=db.transaction(STORE,"readwrite").objectStore(STORE).put(item);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)});db.close()}
async function removeItem(id:string){const db=await openDb();await new Promise<void>((resolve,reject)=>{const request=db.transaction(STORE,"readwrite").objectStore(STORE).delete(id);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)});db.close()}
async function replaceItems(items:InventoryItem[]){const db=await openDb();await new Promise<void>((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite"),store=tx.objectStore(STORE);store.clear();items.forEach(item=>store.put(item));tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)});db.close()}
function compressPhoto(file:File):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error("Bild konnte nicht gelesen werden."));image.onload=()=>{const scale=Math.min(1,1200/Math.max(image.width,image.height)),canvas=document.createElement("canvas");canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext("2d")?.drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.8))};image.src=String(reader.result)};reader.readAsDataURL(file)})}
const empty=(room:string):Omit<InventoryItem,"id"|"updatedAt">=>({title:"",description:"",room,width:1,depth:.5,height:.8,quantity:1,includeInPlan:true,photo:undefined});
const metric=(value:number)=>value.toFixed(2).replace(".",",");

export default function InventoryPanel({roomNames,onPlace}:{roomNames:string[];onPlace:(item:InventoryItem)=>void}){
 const [items,setItems]=useState<InventoryItem[]>([]),[form,setForm]=useState(empty(roomNames[0])),[editing,setEditing]=useState<string|null>(null),[filter,setFilter]=useState("Alle Räume"),[message,setMessage]=useState("");
 const importRef=useRef<HTMLInputElement>(null);useEffect(()=>{readItems().then(setItems).catch(()=>setMessage("Inventar konnte nicht geladen werden."))},[]);
 const filtered=useMemo(()=>items.filter(item=>filter==="Alle Räume"||item.room===filter),[items,filter]),count=items.reduce((sum,item)=>sum+item.quantity,0);
 const save=async(event:React.FormEvent)=>{event.preventDefault();if(!form.title.trim())return;const item:InventoryItem={...form,title:form.title.trim(),id:editing||crypto.randomUUID(),updatedAt:new Date().toISOString()};await writeItem(item);setItems(current=>[...current.filter(value=>value.id!==item.id),item].sort((a,b)=>a.room.localeCompare(b.room)||a.title.localeCompare(b.title)));setForm(empty(form.room));setEditing(null);setMessage("Möbel gespeichert")};
 const edit=(item:InventoryItem)=>{const {id,updatedAt,...data}=item;void id;void updatedAt;setForm({...data,includeInPlan:data.includeInPlan!==false});setEditing(item.id);window.scrollTo({top:0,behavior:"smooth"})};
 const remove=async(item:InventoryItem)=>{if(!confirm(`„${item.title}“ aus dem Inventar löschen?`))return;await removeItem(item.id);setItems(current=>current.filter(value=>value.id!==item.id))};
 const photo=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;if(file.size>15_000_000){setMessage("Das Foto ist grösser als 15 MB.");return}setMessage("Foto wird vorbereitet …");const prepared=await compressPhoto(file);setForm(current=>({...current,photo:prepared}));setMessage("")};
 const backup=()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),items},null,2)],{type:"application/json"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="wohnungsplaner-inventar.json";link.click();URL.revokeObjectURL(link.href)};
 const restore=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text());if(!Array.isArray(parsed.items))throw new Error();const imported=parsed.items.map((item:InventoryItem)=>({...item,includeInPlan:item.includeInPlan!==false}));await replaceItems(imported);setItems(imported);setMessage(`${imported.length} Einträge importiert`)}catch{setMessage("Diese Inventardatei ist ungültig.")}event.target.value=""};
 const pdf=()=>{if(!items.length){setMessage("Erfasse zuerst mindestens ein Möbel.");return}const doc=new jsPDF({unit:"mm",format:"a4"}),pageWidth=210,pageHeight=297,margin=16;let y=18;const footer=()=>{doc.setFontSize(8);doc.setTextColor(110);doc.text(`Umzugsinventar · Seite ${doc.getNumberOfPages()}`,margin,pageHeight-9)},newPage=()=>{footer();doc.addPage();y=17};doc.setFillColor(219,231,101);doc.rect(0,0,pageWidth,7,"F");doc.setTextColor(36,35,31);doc.setFont("helvetica","bold");doc.setFontSize(21);doc.text("Umzugsinventar",margin,y);y+=7;doc.setFont("helvetica","normal");doc.setFontSize(9);doc.setTextColor(95);doc.text(`Wohnung Hombrechtikon · erstellt am ${new Date().toLocaleDateString("de-CH")}`,margin,y);y+=9;doc.setTextColor(36);doc.setFontSize(10);doc.text(`${items.length} Positionen · ${count} Möbelstücke`,margin,y);y+=10;roomNames.map(room=>[room,items.filter(item=>item.room===room)] as const).filter(([,values])=>values.length).forEach(([room,values])=>{if(y>260)newPage();doc.setFillColor(235,230,220);doc.roundedRect(margin,y,pageWidth-margin*2,9,1.5,1.5,"F");doc.setFont("helvetica","bold");doc.setFontSize(11);doc.setTextColor(36);doc.text(room,margin+3,y+6);y+=13;values.forEach(item=>{const description=doc.splitTextToSize(item.description||"Keine Beschreibung",item.photo?116:154),height=Math.max(item.photo?31:22,18+description.length*4);if(y+height>279)newPage();if(item.photo)try{doc.addImage(item.photo,"JPEG",margin,y,34,27,undefined,"FAST")}catch{doc.setFontSize(8);doc.setTextColor(120);doc.text("Foto nicht verfügbar",margin,y+13)}const x=margin+(item.photo?40:0);doc.setFont("helvetica","bold");doc.setFontSize(11);doc.setTextColor(36);doc.text(`${item.quantity}× ${item.title}`,x,y+5);doc.setFont("helvetica","normal");doc.setFontSize(9);doc.setTextColor(75);doc.text(`B × T × H: ${metric(item.width)} × ${metric(item.depth)} × ${metric(item.height)} m`,x,y+11);doc.setFontSize(8.5);doc.setTextColor(105);doc.text(description,x,y+17);y+=height;doc.setDrawColor(210);doc.line(margin,y-2,pageWidth-margin,y-2)});y+=3});footer();doc.save(`umzugsinventar-${new Date().toISOString().slice(0,10)}.pdf`)};
 return <section className="inventoryPage"><div className="inventoryIntro"><div><p className="kicker">MÖBEL & UMZUG</p><h2>Inventarliste</h2><p>Fotos und Angaben bleiben in diesem Browser gespeichert. Mit Sicherung und Import könnt ihr das Inventar zwischen Geräten übertragen.</p></div><div className="inventoryStats"><strong>{count}</strong><span>Möbelstücke</span><strong>{items.length}</strong><span>Positionen</span></div></div><div className="inventoryGrid">
  <form className="inventoryForm" onSubmit={save}><div className="formHead"><div><p className="kicker">{editing?"EINTRAG BEARBEITEN":"NEUES MÖBEL"}</p><h3>{editing?form.title:"Möbel erfassen"}</h3></div>{editing&&<button type="button" className="textButton" onClick={()=>{setEditing(null);setForm(empty(form.room))}}>Abbrechen</button>}</div><label>Titel<input required value={form.title} placeholder="z. B. Sideboard Eiche" onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Beschreibung<textarea rows={3} value={form.description} placeholder="Material, Zustand, Besonderheiten …" onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Raum<select value={form.room} onChange={e=>setForm({...form,room:e.target.value})}>{roomNames.map(room=><option key={room}>{room}</option>)}</select></label><div className="measureFields"><label>Breite (m)<input type="number" min="0.01" step="0.01" required value={form.width} onChange={e=>setForm({...form,width:+e.target.value})}/></label><label>Tiefe (m)<input type="number" min="0.01" step="0.01" required value={form.depth} onChange={e=>setForm({...form,depth:+e.target.value})}/></label><label>Höhe (m)<input type="number" min="0.01" step="0.01" required value={form.height} onChange={e=>setForm({...form,height:+e.target.value})}/></label><label>Anzahl<input type="number" min="1" step="1" required value={form.quantity} onChange={e=>setForm({...form,quantity:+e.target.value})}/></label></div><label className="planCheckbox"><input type="checkbox" checked={form.includeInPlan} onChange={e=>setForm({...form,includeInPlan:e.target.checked})}/><span><strong>Gehört in den Raumplan</strong><small>Deaktivieren für reine Inventarisierung</small></span></label><label className="photoField">Foto<input type="file" accept="image/jpeg,image/png,image/webp" onChange={photo}/><span>{form.photo?"Foto ersetzen":"Foto auswählen"}</span></label>{form.photo&&<div className="photoPreview"><img src={form.photo} alt="Vorschau des Möbels"/><button type="button" onClick={()=>setForm({...form,photo:undefined})}>Foto entfernen</button></div>}<button className="primaryButton" type="submit">{editing?"Änderungen speichern":"Zum Inventar hinzufügen"}</button>{message&&<p className="formMessage" role="status">{message}</p>}</form>
  <div className="inventoryList"><div className="listTools"><label>Filtern<select value={filter} onChange={e=>setFilter(e.target.value)}><option>Alle Räume</option>{roomNames.map(room=><option key={room}>{room}</option>)}</select></label><div><button onClick={backup} disabled={!items.length}>Sicherung</button><button onClick={()=>importRef.current?.click()}>Import</button><input ref={importRef} hidden type="file" accept="application/json" onChange={restore}/><button className="pdfButton" onClick={pdf} disabled={!items.length}>PDF erstellen</button></div></div>{!filtered.length?<div className="emptyInventory"><strong>Noch keine Möbel erfasst.</strong><span>Der erste Eintrag erscheint hier und später in der PDF.</span></div>:<div className="inventoryCards">{filtered.map(item=><article key={item.id} className="inventoryCard">{item.photo?<img src={item.photo} alt=""/>:<div className="photoPlaceholder">Kein Foto</div>}<div className="cardBody"><div className="cardTop"><div><span>{item.room}</span><h3>{item.quantity>1?`${item.quantity}× `:""}{item.title}</h3></div><div className="cardActions"><button onClick={()=>edit(item)}>Bearbeiten</button><button onClick={()=>remove(item)}>Löschen</button></div></div><p>{item.description||"Keine Beschreibung"}</p><strong className="dimensions">B {metric(item.width)} × T {metric(item.depth)} × H {metric(item.height)} m</strong>{item.includeInPlan!==false?<button className="placeButton" onClick={()=>onPlace(item)}>Im Raumplan platzieren</button>:<span className="inventoryOnly">Nur Inventar · nicht im Raumplan</span>}</div></article>)}</div>}</div>
 </div></section>;
}
