"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import "./room.css";
type Pt=[number,number]; type Furniture={id:number;name:string;x:number;y:number;w:number;d:number;h:number;rot:number;color:string};
const rooms:{name:string;poly:Pt[];color:string}[]=[
 {name:"Wohnen / Essen",poly:[[0,0],[7.9,0],[7.9,7.82],[3.3,7.82],[3.3,8.15],[0,8.15]],color:"#d9cbb7"},
 {name:"Küche",poly:[[5.15,4.85],[7.9,4.85],[7.9,7.82],[5.15,7.82]],color:"#c7b69e"},
 {name:"Kind 2",poly:[[0,8.15],[3.51,8.15],[3.51,11.45],[0,11.45]],color:"#d4c4ad"},
 {name:"Kind 1",poly:[[0,11.57],[3.51,11.57],[3.51,15.37],[0,15.37]],color:"#d1c0a7"},
 {name:"Reduit",poly:[[4.62,7.9],[7.9,7.9],[7.9,11.19],[4.62,11.19]],color:"#c9b89f"},
 {name:"Bad",poly:[[3.63,11.2],[5.85,11.2],[5.85,13.82],[3.63,13.82]],color:"#aebbb7"},
 {name:"WC",poly:[[5.97,11.2],[7.9,11.2],[7.9,13.82],[5.97,13.82]],color:"#a9b7b3"},
 {name:"Entrée",poly:[[3.63,8.25],[7.9,8.25],[7.9,11.2],[3.63,11.2]],color:"#c1b39f"},
 {name:"Büro",poly:[[8.15,0],[12.25,0],[12.25,2.93],[8.15,2.93]],color:"#d8c9b3"},
 {name:"Eltern",poly:[[12.37,0],[16.05,0],[16.05,4.9],[12.37,4.9]],color:"#d2bea7"},
 {name:"Gang Büro / Eltern",poly:[[7.9,2.93],[12.25,2.93],[12.25,4.78],[7.9,4.78]],color:"#c2b5a3"},
 {name:"Nische Büro",poly:[[8.15,2.93],[9.03,2.93],[9.03,3.71],[8.15,3.]],color:"#b8aa97"},
 {name:"Nische Eltern",poly:[[11.49,3.92],[12.25,3.92],[12.25,4.78],[11.49,4.78]],color:"#b8aa97"},
 {name:"Dusche",poly:[[12.37,4.9],[14.67,4.9],[14.67,6.9],[12.37,6.9]],color:"#a8b8b5"},
 {name:"Gang Dusche",poly:[[14.82,4.9],[16.05,4.9],[16.05,6.9],[14.82,6.9]],color:"#c2b5a3"},
];
const walls:[Pt,Pt][]=[[[0,0],[7.9,0]],[[0,0],[0,15.56]],[[0,15.56],[7.9,15.56]],[[7.9,6.9],[7.9,13.82]],[[0,8.15],[3.51,8.15]],[[0,11.57],[3.51,11.57]],[[3.51,8.15],[3.51,13.82]],[[3.63,11.2],[7.9,11.2]],[[5.91,11.2],[5.91,13.82]],[[3.63,13.82],[7.9,13.82]],[[4.62,7.9],[7.9,7.9]],[[4.62,7.9],[4.62,11.19]],[[3.63,8.25],[7.9,8.25]],[[8.15,0],[16.05,0]],[[16.05,0],[16.05,6.9]],[[12.37,0],[12.37,2.93]],[[8.15,0],[8.15,2.93]],[[8.15,2.93],[11.49,2.93]],[[12.25,2.93],[12.37,2.93]],[[7.9,4.78],[11.49,4.78]],[[12.25,4.78],[12.25,4.9]],[[12.37,4.9],[14.67,4.9]],[[14.82,4.9],[16.05,4.9]],[[12.37,6.9],[16.05,6.9]],[[12.37,4.9],[12.37,6.9]],[[14.67,4.9],[14.67,6.9]],[[14.82,4.9],[14.82,6.9]],[[9.03,2.93],[9.03,3.71]],[[11.49,3.92],[11.49,4.78]]];
const starter:Furniture[]=[{id:1,name:"Sofa",x:1,y:3.1,w:2.2,d:.9,h:.78,rot:0,color:"#758a7b"},{id:2,name:"Esstisch",x:4.7,y:2.2,w:1.8,d:.9,h:.76,rot:0,color:"#9b714f"},{id:3,name:"Bett",x:13.2,y:1.5,w:2,d:1.6,h:.5,rot:0,color:"#c87558"},{id:4,name:"Schreibtisch",x:9.4,y:1.25,w:1.4,d:.7,h:.75,rot:0,color:"#9b714f"}];
const catalog=[{name:"Sofa",w:2.2,d:.9,h:.78,color:"#758a7b"},{name:"Tisch",w:1.8,d:.9,h:.76,color:"#9b714f"},{name:"Stuhl",w:.48,d:.48,h:.82,color:"#c99b55"},{name:"Bett",w:2,d:1.6,h:.5,color:"#c87558"},{name:"Schrank",w:1.2,d:.6,h:2.1,color:"#7f725f"}];
function proj(x:number,y:number,z:number,w:number,h:number,yaw:number,zoom:number,top:boolean,center:Pt):Pt{const c=Math.cos(yaw),s=Math.sin(yaw),dx=x-center[0],dy=center[1]-y,X=dx*c-dy*s,Y=dx*s+dy*c;return top?[w/2+X*zoom,h/2+Y*zoom]:[w/2+X*zoom,h*.53+Y*zoom*.42-z*zoom*.78]}
function corners(f:Furniture):Pt[]{const c=Math.cos(f.rot),s=Math.sin(f.rot),a:[[number,number],[number,number],[number,number],[number,number]]=[[-f.w/2,-f.d/2],[f.w/2,-f.d/2],[f.w/2,f.d/2],[-f.w/2,f.d/2]];return a.map(([x,y])=>[f.x+x*c-y*s,f.y+x*s+y*c])}

export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null),drag=useRef<{id:number;sx:number;sy:number;ox:number;oy:number}|null>(null); const [yaw,setYaw]=useState(-.58),[zoom,setZoom]=useState(29),[top,setTop]=useState(false),[selected,setSelected]=useState<number|null>(1),[notice,setNotice]=useState(""),[focus,setFocus]=useState("Gesamtwohnung");
 const [items,setItems]=useState<Furniture[]>(starter);
 const focusedRoom=rooms.find(r=>r.name===focus), focusXs=focusedRoom?.poly.map(p=>p[0]),focusYs=focusedRoom?.poly.map(p=>p[1]);
 const center:Pt=focusedRoom&&focusXs&&focusYs?[(Math.min(...focusXs)+Math.max(...focusXs))/2,(Math.min(...focusYs)+Math.max(...focusYs))/2]:[8.225,7.78];
 useEffect(()=>{try{const hash=location.hash.slice(1);const raw=hash?JSON.parse(decodeURIComponent(atob(hash))):JSON.parse(localStorage.getItem("raumplan")||"null");if(Array.isArray(raw))setItems(raw)}catch{}},[]);
 useEffect(()=>{localStorage.setItem("raumplan",JSON.stringify(items))},[items]);
 const draw=useCallback(()=>{const c=canvas.current;if(!c)return;const dpr=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=r.width*dpr;c.height=r.height*dpr;const g=c.getContext("2d")!;g.scale(dpr,dpr);g.clearRect(0,0,r.width,r.height);const P=(p:Pt,z=0)=>proj(p[0],p[1],z,r.width,r.height,yaw,zoom,top,center);const face=(p:Pt[],fill:string,stroke="#746b60")=>{g.beginPath();p.forEach((q,i)=>i?g.lineTo(...q):g.moveTo(...q));g.closePath();g.fillStyle=fill;g.fill();g.strokeStyle=stroke;g.lineWidth=1;g.stroke()};rooms.forEach(x=>{g.globalAlpha=focus==="Gesamtwohnung"||x.name===focus?1:.16;face(x.poly.map(q=>P(q)),x.color)});g.globalAlpha=1;if(!top)walls.forEach(([a,b])=>face([P(a),P(b),P(b,2.39),P(a,2.39)],"rgba(244,240,232,.78)","#958b7e"));
 items.forEach(f=>{const base=corners(f),lower=base.map(q=>P(q)),upper=base.map(q=>P(q,f.h));if(!top){face([lower[1],lower[2],upper[2],upper[1]],f.color);face([lower[2],lower[3],upper[3],upper[2]],f.color)}face(upper,f.color,selected===f.id?"#dbe765":"#534e47");if(selected===f.id){g.strokeStyle="#24231f";g.lineWidth=2;g.stroke()}});
 rooms.forEach(x=>{if(!x.name||(focus!=="Gesamtwohnung"&&x.name!==focus))return;const px=x.poly.reduce((n,p)=>n+p[0],0)/x.poly.length,py=x.poly.reduce((n,p)=>n+p[1],0)/x.poly.length,q=P([px,py],.02),xs=x.poly.map(p=>p[0]),ys=x.poly.map(p=>p[1]);g.fillStyle="#39362f";g.font="600 10px Arial";g.textAlign="center";g.fillText(x.name,q[0],q[1]);if(top){g.font="9px Arial";g.fillText(`${(Math.max(...xs)-Math.min(...xs)).toFixed(2).replace(".",",")} × ${(Math.max(...ys)-Math.min(...ys)).toFixed(2).replace(".",",")} m`,q[0],q[1]+13)}});if(top&&focus==="Gesamtwohnung"){const dim=(a:Pt,b:Pt,label:string)=>{const p=P(a),q=P(b),ang=Math.atan2(q[1]-p[1],q[0]-p[0]);g.strokeStyle="#5e5850";g.lineWidth=1;g.beginPath();g.moveTo(...p);g.lineTo(...q);g.stroke();[p,q].forEach(t=>{g.beginPath();g.moveTo(t[0]-4*Math.sin(ang),t[1]+4*Math.cos(ang));g.lineTo(t[0]+4*Math.sin(ang),t[1]-4*Math.cos(ang));g.stroke()});g.save();g.translate((p[0]+q[0])/2,(p[1]+q[1])/2);g.rotate(ang);g.fillStyle="#f7f4ed";g.fillRect(-43,-10,86,15);g.fillStyle="#302d29";g.font="600 10px Arial";g.textAlign="center";g.fillText(label,0,1);g.restore()};dim([0,-.6],[16.45,-.6],"16,45 m gesamt");dim([-.6,0],[-.6,15.56],"15,56 m gesamt")}},[items,selected,top,yaw,zoom,focus,center]);
 useEffect(()=>{draw();const fn=()=>draw();addEventListener("resize",fn);return()=>removeEventListener("resize",fn)},[draw]);
 const locate=(e:React.PointerEvent)=>{const r=canvas.current!.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;let hit:null|Furniture=null,best=1e9;items.forEach(f=>{const p=proj(f.x,f.y,top?0:f.h,r.width,r.height,yaw,zoom,top,center),d=(p[0]-mx)**2+(p[1]-my)**2;if(d<best&&d<(Math.max(f.w,f.d)*zoom*.8+18)**2){hit=f;best=d}});return{r,mx,my,hit}}
 const down=(e:React.PointerEvent)=>{const q=locate(e);if(q.hit){setSelected(q.hit.id);drag.current={id:q.hit.id,sx:q.mx,sy:q.my,ox:q.hit.x,oy:q.hit.y};canvas.current!.setPointerCapture(e.pointerId)}};
 const move=(e:React.PointerEvent)=>{if(!drag.current)return;const r=canvas.current!.getBoundingClientRect(),dx=e.clientX-r.left-drag.current.sx,dy=e.clientY-r.top-drag.current.sy,c=Math.cos(yaw),s=Math.sin(yaw),worldX=dx/zoom,worldY=dy/(zoom*(top?1:.42));setItems(v=>v.map(f=>f.id===drag.current!.id?{...f,x:Math.max(.2,Math.min(15.85,drag.current!.ox+worldX*c+worldY*s)),y:Math.max(.2,Math.min(15.36,drag.current!.oy+worldX*s-worldY*c))}:f))};
 const add=(c:typeof catalog[number])=>{const id=Date.now();setItems(v=>[...v,{...c,id,x:center[0],y:center[1],rot:0}]);setSelected(id)};
 const chooseFocus=(name:string)=>{setFocus(name);if(name==="Gesamtwohnung"){setZoom(29);return}const room=rooms.find(r=>r.name===name);if(!room)return;const xs=room.poly.map(p=>p[0]),ys=room.poly.map(p=>p[1]),span=Math.max(Math.max(...xs)-Math.min(...xs),Math.max(...ys)-Math.min(...ys));setZoom(Math.min(56,Math.max(36,180/span)))};
 const update=(key:"rot"|"w"|"d",v:number)=>setItems(x=>x.map(f=>f.id===selected?{...f,[key]:v}:f));const active=items.find(x=>x.id===selected);
 const share=async()=>{const url=location.href.split("#")[0]+"#"+btoa(encodeURIComponent(JSON.stringify(items)));history.replaceState(null,"",url);try{await navigator.clipboard.writeText(url);setNotice("Link kopiert") }catch{setNotice("Link ist bereit")};setTimeout(()=>setNotice(""),2200)};
 return <main><header><div><span className="eyebrow">HOMBRECHTIKON · WOHNUNG</span><h1>Raumplaner</h1></div><div className="headActions"><button className="share" onClick={share}>{notice||"Plan teilen"}</button><span className="status">Grundriss v0.4</span></div></header>
 <section className="workspace"><aside><p className="kicker">RAUMANSICHT</p><h2>Gemeinsam<br/>einrichten.</h2><p className="intro">Einen Raum oder Gang einzeln fokussieren und dort Möbel platzieren.</p><label className="roomPicker">Bereich<select value={focus} onChange={e=>chooseFocus(e.target.value)}><option>Gesamtwohnung</option>{rooms.filter(r=>r.name).map(r=><option key={r.name}>{r.name}</option>)}</select></label><p className="kicker catalogTitle">MÖBELKATALOG</p><div className="catalog">{catalog.map(c=><button key={c.name} onClick={()=>add(c)}><i style={{background:c.color}}/>+ {c.name}</button>)}</div>{active&&<div className="editor"><div className="editorTitle"><strong>{active.name}</strong><button aria-label="Möbel löschen" onClick={()=>{setItems(x=>x.filter(f=>f.id!==active.id));setSelected(null)}}>×</button></div><label>Drehung <span>{Math.round(active.rot*180/Math.PI)}°</span><input type="range" min="0" max="6.28" step=".05" value={active.rot} onChange={e=>update("rot",+e.target.value)}/></label><label>Breite <span>{active.w.toFixed(2)} m</span><input type="range" min=".3" max="3" step=".05" value={active.w} onChange={e=>update("w",+e.target.value)}/></label><label>Tiefe <span>{active.d.toFixed(2)} m</span><input type="range" min=".3" max="2.5" step=".05" value={active.d} onChange={e=>update("d",+e.target.value)}/></label></div>}<div className="assumption">Raumhöhe <strong>2,39 m*</strong><small>* Annahme gemäss Schnitt A–A</small></div></aside>
 <div className="stage"><div className="viewbar"><button className={!top?"active":""} onClick={()=>setTop(false)}>3D</button><button className={top?"active":""} onClick={()=>setTop(true)}>Grundriss</button></div><canvas ref={canvas} onPointerDown={down} onPointerMove={move} onPointerUp={()=>drag.current=null}/><div className="viewcontrols"><label>Drehen <input type="range" min="-3.14" max="3.14" step=".01" value={yaw} onChange={e=>setYaw(+e.target.value)}/></label><label>Zoom <input type="range" min="16" max="60" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label></div><div className="hint">Möbel antippen und ziehen</div></div></section></main>
}
