"use client";

import { useCallback, useEffect, useRef, useState } from "react";
type Pt=[number,number]; type Furniture={id:number;name:string;x:number;y:number;w:number;d:number;h:number;rot:number;color:string};
const rooms:{name:string;poly:Pt[];color:string}[]=[
 {name:"Wohnen / Essen",poly:[[0,0],[7.9,0],[7.9,7.82],[3.3,7.82],[3.3,11.17],[0,11.17]],color:"#d9cbb7"},
 {name:"Küche",poly:[[5.15,4.85],[7.9,4.85],[7.9,7.82],[5.15,7.82]],color:"#c7b69e"},
 {name:"Kind 2",poly:[[0,11.17],[3.51,11.17],[3.51,14.47],[0,14.47]],color:"#d4c4ad"},
 {name:"Kind 1",poly:[[0,14.47],[3.51,14.47],[3.51,18.27],[0,18.27]],color:"#d1c0a7"},
 {name:"Reduit",poly:[[4.62,8],[7.9,8],[7.9,11.29],[4.62,11.29]],color:"#c9b89f"},
 {name:"Bad",poly:[[3.63,14.25],[5.85,14.25],[5.85,16.87],[3.63,16.87]],color:"#aebbb7"},
 {name:"WC",poly:[[5.97,14.25],[7.9,14.25],[7.9,16.87],[5.97,16.87]],color:"#a9b7b3"},
 {name:"Entrée",poly:[[3.63,11.29],[7.9,11.29],[7.9,14.25],[3.63,14.25]],color:"#c1b39f"},
 {name:"Büro",poly:[[8.15,0],[12.25,0],[12.25,2.93],[8.15,2.93]],color:"#d8c9b3"},
 {name:"Eltern",poly:[[12.37,0],[16.05,0],[16.05,4.5],[12.37,4.5]],color:"#d2bea7"},
 {name:"Dusche",poly:[[11.7,4.5],[14.1,4.5],[14.1,6.55],[11.7,6.55]],color:"#a8b8b5"},
 {name:"",poly:[[7.9,2.93],[11.7,2.93],[11.7,6.55],[7.9,6.55]],color:"#c2b5a3"},
];
const walls:[Pt,Pt][]=[[[0,0],[7.9,0]],[[0,0],[0,18.27]],[[0,18.27],[7.9,18.27]],[[7.9,6.55],[7.9,16.87]],[[0,11.17],[3.51,11.17]],[[0,14.47],[3.51,14.47]],[[3.51,11.17],[3.51,16.87]],[[3.63,14.25],[7.9,14.25]],[[5.91,14.25],[5.91,16.87]],[[3.63,16.87],[7.9,16.87]],[[4.62,8],[7.9,8]],[[4.62,8],[4.62,11.29]],[[3.63,11.29],[7.9,11.29]],[[8.15,0],[16.05,0]],[[16.05,0],[16.05,4.5]],[[12.37,0],[12.37,4.5]],[[8.15,0],[8.15,2.93]],[[8.15,2.93],[11.7,2.93]],[[11.7,2.93],[11.7,6.55]],[[11.7,4.5],[16.05,4.5]],[[11.7,6.55],[14.1,6.55]],[[14.1,4.5],[14.1,6.55]]];
const starter:Furniture[]=[{id:1,name:"Sofa",x:1,y:3.1,w:2.2,d:.9,h:.78,rot:0,color:"#758a7b"},{id:2,name:"Esstisch",x:4.7,y:2.2,w:1.8,d:.9,h:.76,rot:0,color:"#9b714f"},{id:3,name:"Bett",x:13.2,y:1.5,w:2,d:1.6,h:.5,rot:0,color:"#c87558"},{id:4,name:"Schreibtisch",x:9.4,y:1.25,w:1.4,d:.7,h:.75,rot:0,color:"#9b714f"}];
const catalog=[{name:"Sofa",w:2.2,d:.9,h:.78,color:"#758a7b"},{name:"Tisch",w:1.8,d:.9,h:.76,color:"#9b714f"},{name:"Stuhl",w:.48,d:.48,h:.82,color:"#c99b55"},{name:"Bett",w:2,d:1.6,h:.5,color:"#c87558"},{name:"Schrank",w:1.2,d:.6,h:2.1,color:"#7f725f"}];
function proj(x:number,y:number,z:number,w:number,h:number,yaw:number,zoom:number,top:boolean):Pt{const cx=8.05,cy=9.1,c=Math.cos(yaw),s=Math.sin(yaw),X=(x-cx)*c-(y-cy)*s,Y=(x-cx)*s+(y-cy)*c;return top?[w/2+X*zoom,h/2+Y*zoom]:[w/2+X*zoom,h*.53+Y*zoom*.42-z*zoom*.78]}
function corners(f:Furniture):Pt[]{const c=Math.cos(f.rot),s=Math.sin(f.rot),a:[[number,number],[number,number],[number,number],[number,number]]=[[-f.w/2,-f.d/2],[f.w/2,-f.d/2],[f.w/2,f.d/2],[-f.w/2,f.d/2]];return a.map(([x,y])=>[f.x+x*c-y*s,f.y+x*s+y*c])}

export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null),drag=useRef<{id:number;sx:number;sy:number;ox:number;oy:number}|null>(null); const [yaw,setYaw]=useState(-.58),[zoom,setZoom]=useState(29),[top,setTop]=useState(false),[selected,setSelected]=useState<number|null>(1),[notice,setNotice]=useState("");
 const [items,setItems]=useState<Furniture[]>(starter);
 useEffect(()=>{try{const hash=location.hash.slice(1);const raw=hash?JSON.parse(decodeURIComponent(atob(hash))):JSON.parse(localStorage.getItem("raumplan")||"null");if(Array.isArray(raw))setItems(raw)}catch{}},[]);
 useEffect(()=>{localStorage.setItem("raumplan",JSON.stringify(items))},[items]);
 const draw=useCallback(()=>{const c=canvas.current;if(!c)return;const dpr=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=r.width*dpr;c.height=r.height*dpr;const g=c.getContext("2d")!;g.scale(dpr,dpr);g.clearRect(0,0,r.width,r.height);const P=(p:Pt,z=0)=>proj(p[0],p[1],z,r.width,r.height,yaw,zoom,top);const face=(p:Pt[],fill:string,stroke="#746b60")=>{g.beginPath();p.forEach((q,i)=>i?g.lineTo(...q):g.moveTo(...q));g.closePath();g.fillStyle=fill;g.fill();g.strokeStyle=stroke;g.lineWidth=1;g.stroke()};rooms.forEach(x=>face(x.poly.map(q=>P(q)),x.color));if(!top)walls.forEach(([a,b])=>face([P(a),P(b),P(b,2.39),P(a,2.39)],"rgba(244,240,232,.78)","#958b7e"));
 items.forEach(f=>{const base=corners(f),lower=base.map(q=>P(q)),upper=base.map(q=>P(q,f.h));if(!top){face([lower[1],lower[2],upper[2],upper[1]],f.color);face([lower[2],lower[3],upper[3],upper[2]],f.color)}face(upper,f.color,selected===f.id?"#dbe765":"#534e47");if(selected===f.id){g.strokeStyle="#24231f";g.lineWidth=2;g.stroke()}});
 rooms.forEach(x=>{const px=x.poly.reduce((n,p)=>n+p[0],0)/x.poly.length,py=x.poly.reduce((n,p)=>n+p[1],0)/x.poly.length,q=P([px,py],.02);g.fillStyle="#39362f";g.font="600 10px Arial";g.textAlign="center";g.fillText(x.name,q[0],q[1])})},[items,selected,top,yaw,zoom]);
 useEffect(()=>{draw();const fn=()=>draw();addEventListener("resize",fn);return()=>removeEventListener("resize",fn)},[draw]);
 const locate=(e:React.PointerEvent)=>{const r=canvas.current!.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top;let hit:null|Furniture=null,best=1e9;items.forEach(f=>{const p=proj(f.x,f.y,top?0:f.h,r.width,r.height,yaw,zoom,top),d=(p[0]-mx)**2+(p[1]-my)**2;if(d<best&&d<(Math.max(f.w,f.d)*zoom*.8+18)**2){hit=f;best=d}});return{r,mx,my,hit}}
 const down=(e:React.PointerEvent)=>{const q=locate(e);if(q.hit){setSelected(q.hit.id);drag.current={id:q.hit.id,sx:q.mx,sy:q.my,ox:q.hit.x,oy:q.hit.y};canvas.current!.setPointerCapture(e.pointerId)}};
 const move=(e:React.PointerEvent)=>{if(!drag.current)return;const r=canvas.current!.getBoundingClientRect(),dx=e.clientX-r.left-drag.current.sx,dy=e.clientY-r.top-drag.current.sy,c=Math.cos(yaw),s=Math.sin(yaw),worldX=dx/zoom,worldY=dy/(zoom*(top?1:.42));setItems(v=>v.map(f=>f.id===drag.current!.id?{...f,x:Math.max(.2,Math.min(15.85,drag.current!.ox+worldX*c+worldY*s)),y:Math.max(.2,Math.min(18.07,drag.current!.oy-worldX*s+worldY*c))}:f))};
 const add=(c:typeof catalog[number])=>{const id=Date.now();setItems(v=>[...v,{...c,id,x:3.7,y:5.5,rot:0}]);setSelected(id)};
 const update=(key:"rot"|"w"|"d",v:number)=>setItems(x=>x.map(f=>f.id===selected?{...f,[key]:v}:f));const active=items.find(x=>x.id===selected);
 const share=async()=>{const url=location.href.split("#")[0]+"#"+btoa(encodeURIComponent(JSON.stringify(items)));history.replaceState(null,"",url);try{await navigator.clipboard.writeText(url);setNotice("Link kopiert") }catch{setNotice("Link ist bereit")};setTimeout(()=>setNotice(""),2200)};
 return <main><header><div><span className="eyebrow">HOMBRECHTIKON · WOHNUNG</span><h1>Raumplaner</h1></div><div className="headActions"><button className="share" onClick={share}>{notice||"Plan teilen"}</button><span className="status">Grundriss v0.3</span></div></header>
 <section className="workspace"><aside><p className="kicker">MÖBELKATALOG</p><h2>Gemeinsam<br/>einrichten.</h2><p className="intro">Möbel hinzufügen, im Plan verschieben und den aktuellen Stand per Link teilen.</p><div className="catalog">{catalog.map(c=><button key={c.name} onClick={()=>add(c)}><i style={{background:c.color}}/>+ {c.name}</button>)}</div>{active&&<div className="editor"><div className="editorTitle"><strong>{active.name}</strong><button aria-label="Möbel löschen" onClick={()=>{setItems(x=>x.filter(f=>f.id!==active.id));setSelected(null)}}>×</button></div><label>Drehung <span>{Math.round(active.rot*180/Math.PI)}°</span><input type="range" min="0" max="6.28" step=".05" value={active.rot} onChange={e=>update("rot",+e.target.value)}/></label><label>Breite <span>{active.w.toFixed(2)} m</span><input type="range" min=".3" max="3" step=".05" value={active.w} onChange={e=>update("w",+e.target.value)}/></label><label>Tiefe <span>{active.d.toFixed(2)} m</span><input type="range" min=".3" max="2.5" step=".05" value={active.d} onChange={e=>update("d",+e.target.value)}/></label></div>}<div className="assumption">Raumhöhe <strong>2,39 m*</strong><small>* Annahme gemäss Schnitt A–A</small></div></aside>
 <div className="stage"><div className="viewbar"><button className={!top?"active":""} onClick={()=>setTop(false)}>3D</button><button className={top?"active":""} onClick={()=>setTop(true)}>Grundriss</button></div><canvas ref={canvas} onPointerDown={down} onPointerMove={move} onPointerUp={()=>drag.current=null}/><div className="viewcontrols"><label>Drehen <input type="range" min="-3.14" max="3.14" step=".01" value={yaw} onChange={e=>setYaw(+e.target.value)}/></label><label>Zoom <input type="range" min="16" max="42" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label></div><div className="hint">Möbel antippen und ziehen</div></div></section></main>
}
